"use client";

import {
  copyResultsTable,
  downloadCalculatorPdf,
  downloadResultsCsv,
} from "@/lib/calculators/pdf-export";
import { trackEvent, trackExport, trackCopyResult } from "@/lib/analytics/events";
import { useCalculatorMeta } from "@/components/calculator/CalculatorMetaContext";
import { CONTACT_EMAIL } from "@/lib/legal/constants";
import { useToast } from "@/components/ui/ToastProvider";

type ExportButtonsProps = {
  title: string;
  standard?: string;
  inputRows: { label: string; value: string }[];
  resultRows: { label: string; value: string }[];
  variant?: "stack" | "inline";
};

function FileIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor" className={className}>
      <path d="M5.5 2A1.5 1.5 0 004 3.5v13A1.5 1.5 0 005.5 18h9a1.5 1.5 0 001.5-1.5V7.121a1.5 1.5 0 00-.44-1.06l-3.621-3.62A1.5 1.5 0 0010.879 2H5.5zm5 1.5v3A1.5 1.5 0 0012 8h3v8.5a.5.5 0 01-.5.5h-9a.5.5 0 01-.5-.5v-13a.5.5 0 01.5-.5h5z" />
    </svg>
  );
}

function CopyIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor" className={className}>
      <path d="M6 2.75A1.75 1.75 0 007.75 1h7.5A1.75 1.75 0 0117 2.75v9.5A1.75 1.75 0 0115.25 14h-1.5v1.25A1.75 1.75 0 0112 17H4.75A1.75 1.75 0 013 15.25v-9.5A1.75 1.75 0 014.75 4H6v-1.25zm1 1.25h5A1.75 1.75 0 0113.75 5.75V13h1.5a.75.75 0 00.75-.75v-9.5a.75.75 0 00-.75-.75h-7.5a.75.75 0 00-.75.75V4zm5.75 1.75a.75.75 0 00-.75-.75H4.75a.75.75 0 00-.75.75v9.5c0 .414.336.75.75.75H12a.75.75 0 00.75-.75v-9.5z" />
    </svg>
  );
}

function tableText(rows: { label: string; value: string }[]) {
  return rows.map((row) => `${row.label}: ${row.value}`).join("\n");
}

export default function ExportButtons({
  title,
  standard,
  inputRows,
  resultRows,
  variant = "stack",
}: ExportButtonsProps) {
  const { showToast } = useToast();
  const meta = useCalculatorMeta();
  const fileBase = title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const calcId = meta.slug || meta.type || fileBase;

  function handlePdf() {
    downloadCalculatorPdf({
      title,
      standard,
      generatedAt: new Date().toLocaleString(),
      inputs: inputRows,
      results: resultRows,
    });
    trackExport(calcId, "pdf", `${fileBase}-report.pdf`);
    trackEvent("file_download", {
      file_extension: "pdf",
      file_name: `${fileBase}-report.pdf`,
      calculator_id: calcId,
    });
    showToast("Field Screening Report PDF ready for export.");
  }

  function handleExcel() {
    downloadResultsCsv(title, [...inputRows, ...resultRows]);
    trackExport(calcId, "excel", `${fileBase}.csv`);
    trackEvent("file_download", {
      file_extension: "csv",
      file_name: `${fileBase}.csv`,
      calculator_id: calcId,
    });
  }

  async function handleCopy() {
    await copyResultsTable(resultRows);
    trackCopyResult(calcId, {
      content_type: "calculator_results_table",
      row_count: resultRows.length,
    });
    trackEvent("copy_data", {
      content_type: "calculator_results",
      calculator_id: calcId,
    });
  }

  function handleEmail() {
    const body = [
      title,
      standard ? `Standard: ${standard}` : "",
      "",
      "Inputs",
      tableText(inputRows),
      "",
      "Results",
      tableText(resultRows),
      "",
      "Generated by FieldEngineersKit. Screening estimate only.",
    ]
      .filter((line) => line !== undefined)
      .join("\n");
    const href = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(`${title} results`)}&body=${encodeURIComponent(body)}`;
    trackEvent("share", {
      method: "email",
      content_type: "calculator_results",
      calculator_id: calcId,
    });
    window.location.href = href;
  }

  const compact = variant === "inline";
  const buttonClass = compact
    ? "inline-flex h-8 items-center justify-center gap-1.5 rounded-md border border-spec-borderStrong bg-spec-bg px-2.5 text-sm font-medium text-spec-text transition-colors hover:bg-spec-panel focus:outline-none focus:ring-2 focus:ring-spec-accent"
    : "flex min-h-11 items-center justify-center gap-1.5 rounded-md border border-spec-borderStrong bg-spec-bg px-2 py-2.5 text-sm font-medium text-spec-text hover:bg-spec-panel md:min-h-12 md:text-base";

  return (
    <div
      className={
        compact
          ? "flex flex-wrap justify-end gap-1"
          : "mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"
      }
    >
      <button type="button" onClick={handlePdf} className={buttonClass}>
        <FileIcon className="h-3.5 w-3.5 text-spec-text2" />
        PDF
      </button>
      <button type="button" onClick={handleExcel} className={buttonClass}>
        <FileIcon className="h-3.5 w-3.5 text-spec-text2" />
        Excel
      </button>
      <button type="button" onClick={handleCopy} className={buttonClass}>
        <CopyIcon className="h-3.5 w-3.5 text-spec-text2" />
        {compact ? "Copy" : (
          <>
            <span className="sm:hidden">Copy</span>
            <span className="hidden sm:inline">Copy table</span>
          </>
        )}
      </button>
      {compact ? null : (
        <button type="button" onClick={handleEmail} className={buttonClass}>
          ✉ Email
        </button>
      )}
    </div>
  );
}
