"use client";

import {
  copyResultsTable,
  downloadCalculatorPdf,
  downloadResultsCsv,
} from "@/lib/calculators/pdf-export";
import { trackEvent, trackExport, trackCopyResult } from "@/lib/analytics/events";
import { useCalculatorMeta } from "@/components/calculator/CalculatorMetaContext";
import { CONTACT_EMAIL } from "@/lib/legal/constants";
import { useToast } from "@/components/ui/ToastProvider";

type ExportButtonsProps = {
  title: string;
  standard?: string;
  inputRows: { label: string; value: string }[];
  resultRows: { label: string; value: string }[];
  variant?: "stack" | "inline";
};

function tableText(rows: { label: string; value: string }[]) {
  return rows.map((row) => `${row.label}: ${row.value}`).join("\n");
}

export default function ExportButtons({
  title,
  standard,
  inputRows,
  resultRows,
  variant = "stack",
}: ExportButtonsProps) {
  const { showToast } = useToast();
  const meta = useCalculatorMeta();
  const fileBase = title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const calcId = meta.slug || meta.type || fileBase;

  function handlePdf() {
    downloadCalculatorPdf({
      title,
      standard,
      generatedAt: new Date().toLocaleString(),
      inputs: inputRows,
      results: resultRows,
    });
    trackExport(calcId, "pdf", `${fileBase}-report.pdf`);
    trackEvent("file_download", {
      file_extension: "pdf",
      file_name: `${fileBase}-report.pdf`,
      calculator_id: calcId,
    });
    showToast("Field Screening Report PDF ready for export.");
  }

  function handleExcel() {
    downloadResultsCsv(title, [...inputRows, ...resultRows]);
    trackExport(calcId, "excel", `${fileBase}.csv`);
    trackEvent("file_download", {
      file_extension: "csv",
      file_name: `${fileBase}.csv`,
      calculator_id: calcId,
    });
  }

  async function handleCopy() {
    await copyResultsTable(resultRows);
    trackCopyResult(calcId, {
      content_type: "calculator_results_table",
      row_count: resultRows.length,
    });
    trackEvent("copy_data", {
      content_type: "calculator_results",
      calculator_id: calcId,
    });
  }

  function handleEmail() {
    const body = [
      title,
      standard ? `Standard: ${standard}` : "",
      "",
      "Inputs",
      tableText(inputRows),
      "",
      "Results",
      tableText(resultRows),
      "",
      "Generated by FieldEngineersKit. Screening estimate only.",
    ]
      .filter((line) => line !== undefined)
      .join("\n");
    const href = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(`${title} results`)}&body=${encodeURIComponent(body)}`;
    trackEvent("share", {
      method: "email",
      content_type: "calculator_results",
      calculator_id: calcId,
    });
    window.location.href = href;
  }

  const compact = variant === "inline";
  const buttonClass = compact
    ? "inline-flex h-8 items-center justify-center rounded border border-spec-borderStrong bg-spec-bg px-2.5 text-sm font-medium text-spec-text transition-colors hover:bg-spec-panel focus:outline-none focus:ring-2 focus:ring-spec-accent"
    : "flex min-h-11 items-center justify-center gap-1.5 rounded-md border border-spec-borderStrong bg-spec-bg px-2 py-2.5 text-sm font-medium text-spec-text hover:bg-spec-panel md:min-h-12 md:text-base";
  const pdfClass = compact
    ? "inline-flex h-8 items-center justify-center rounded bg-spec-accent px-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-spec-accentText focus:outline-none focus:ring-2 focus:ring-spec-accent"
    : "flex min-h-11 items-center justify-center gap-1.5 rounded-md bg-spec-accent px-2 py-2.5 text-sm font-medium text-white hover:bg-spec-accentText md:min-h-12 md:text-base";

  return (
    <div
      className={
        compact
          ? "flex flex-wrap justify-end gap-1"
          : "mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"
      }
    >
      <button type="button" onClick={handlePdf} className={pdfClass}>
        PDF
      </button>
      <button type="button" onClick={handleExcel} className={buttonClass}>
        Excel
      </button>
      <button type="button" onClick={handleCopy} className={buttonClass}>
        {compact ? "Copy" : (
          <>
            <span className="sm:hidden">Copy</span>
            <span className="hidden sm:inline">Copy table</span>
          </>
        )}
      </button>
      {compact ? null : (
        <button type="button" onClick={handleEmail} className={buttonClass}>
          ✉ Email
        </button>
      )}
    </div>
  );
}
