/**
 * Query keys encoded in `/calculator/{slug}/{spec}` — strip from ?query when
 * a SpecRoute match is active. Keep auxiliary keys (units, pressure, …).
 */
export const PATH_OWNED_PARAMS = new Set([
  "nps",
  "sch",
  "schedule",
  "class",
  "class_rating",
  "fluid",
  "material",
  "cat",
  "category",
  "size",
  "fittingType",
  "qty",
  "re",
  "reynoldsNumber",
  "bolts",
  "pattern",
  "hnps",
  "bnps",
  "hsch",
  "bsch",
  "theta",
  "angle",
  "pt",
  "vol",
  "mode",
  "gas",
  "temp",
  "temperature",
  "arr",
  "hs",
  "hf",
  "npshr",
  "ps",
  "q",
  "qunit",
  "dens",
  "etap",
  "etam",
  "hp",
  "visc",
  "sf",
  "mode",
  "n1",
  "n2",
  "d1",
  "d2",
  "head",
  "pwr",
  "hso",
  "dtmax",
  "mcsf",
  "sor",
  "etamin",
  "dp",
  "vmax",
  "cp",
  "sg",
  "qop",
  "hr",
  "n",
  "facing",
  "gasketType",
  "insulationThickness",
  "operatingTemp",
  "ambientTemp",
  "windSpeed",
  "emissivity",
  "orientation",
  "headType",
  "diameter",
  "length",
  "liquidLevel",
  "geometryType",
  "purgeMethod",
  "pipeNps",
  "pipeSchedule",
  "pipeLength",
  "vesselDiameter",
  "vesselLength",
  "customVolume",
  "cycleHighPressure",
  "mixingEfficiency",
  "initialO2",
  "targetO2",
  "purgeFlowRate",
  "materialGroup",
  "flangeClass",
  "designTemperature",
  "space",
  "s63",
  "s125",
  "s250",
  "s500",
  "s1k",
  "s2k",
  "s4k",
  "s8k",
  "rise",
  "run",
  "mat",
  "fluidType",
  "massFlow",
  "cv",
  "p1",
  "p2",
  "orificeDiameter",
  "deltaP",
  "fluidDensity",
  "dynamicViscosity",
  "tap",
  "inputMode",
  "steamQuality",
  "ymax",
  "ins",
  "fluidState",
  "xtFactor",
  "flFactor",
  "specificHeatRatio",
  "vaporPressure",
  "criticalPressure",
  "trim",
  "setPressure",
  "requiredCapacity",
  "overpressurePercent",
  "molecularWeight",
  "relievingTemperature",
  "liquidDensity",
  "specificGravity",
  "co2MolePercent",
  "n2MolePercent",
  "th_in",
  "th_out",
  "tc_in",
  "tc_out",
  "flow",
  "shells",
  "u",
  "fluid_cold",
  "cp_hot",
  "cp_cold",
  "t1",
  "eff",
  "z",
  "mw",
  "k",
  "d",
  "h",
  "ch",
  "sg",
  "ca",
  "e",
  // pipe-branch reinforcement duty fields (encoded in Pattern B path match)
  "sh",
  "sb",
  "sr",
  "legh",
  "legb",
  "w",
  "y",
  "mill",
  // olet fitting dimensions (MSS SP-97 Pattern B)
  "type",
  "runSize",
  "branchSize",
  "rating",
  // pipe steam tracing duty
  "tMaint",
  "tAmb",
  "insThk",
  "pSteam",
  "tracer",
  "wind",
  "maintainTemp",
  "steamPressure",
  // ASME B16.11 forged fittings
  "conn",
  "fitting",
  "rating",
  // ASME VIII-1 UG-32 formed head thickness
  "id",
  "p",
  "alpha",
  "units",
  // ASME VIII-1 UG-37 nozzle reinforcement
  "shell",
  "shellId",
  "shellThk",
  "shellMat",
  "nozThk",
  "nozMat",
  "dout",
  "tp",
  "weld",
  // ISO 281 / ABMA bearing L10h
  "type",
  "c",
  "fr",
  "fa",
  "rpm",
  "x",
  "y",
  "xymode",
  // ASME BTH-1 / AISC lifting lug
  "weight",
  "impact",
  "lugs",
  "angle",
  "thk",
  "rOuter",
  "dHole",
  "dPin",
  "hLug",
  "mat",
  "weldSize",
  "weldLen",
  "electrode",
  // ASME PTC 6 / IAPWS steam turbine power & SSC
  "p1",
  "t1",
  "p2",
  "flow",
  "etaIsen",
  "etaMech",
  "etaGen",
  // DIN 6885 / ASME B17.1 shaft torque & parallel key
  "power",
  "matShaft",
  "matKey",
  "b",
  "length",
  "autokey",
  // API 2000 tank venting
  "dia",
  "height",
  "pumpIn",
  "pumpOut",
  "volatility",
  "env",
  "f",
  "m",
  "lv",
  "lat",
  // ASME B16.34 valve wall & P-T
  "matGroup",
  "press",
  // PSV reaction force (API 520 Part II)
  "disch",
  "flow",
  "gas",
  "mw",
  "k",
  "dlf",
  "patm",
  // ASME B16.21 flat gasket
  "thick",
  "std",
]);

/**
 * Drop keys already encoded in `/calculator/{slug}/{spec}` (nps, class, gasketType, …).
 * Keeps auxiliary state: units, pressure, targetBoltStress, etc.
 */
export function omitPathOwnedSearchParams(
  params: URLSearchParams,
): URLSearchParams {
  const keep = new URLSearchParams();
  params.forEach((value, key) => {
    if (!PATH_OWNED_PARAMS.has(key)) {
      keep.set(key, value);
    }
  });
  return keep;
}

export function searchParamsHavePathOwnedKeys(
  params: URLSearchParams,
): boolean {
  let found = false;
  params.forEach((_value, key) => {
    if (PATH_OWNED_PARAMS.has(key)) found = true;
  });
  return found;
}
